FROM python:3.11-slim

WORKDIR /app

# Устанавливаем зависимости для работы с Excel
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Создаем папку для Excel файлов
RUN mkdir -p excel_files

CMD ["python", "main.py"]